# sudo docker-compose -f docker-compose-dev.yml --env-file .env.dev up

version: '3'
services:
  backend:
    image: backend_test
    container_name: backend_container
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
      - .env.dev:/app/.env.dev
      - ./credentials.json:/app/credentials.json
    environment:
      - ENV=dev

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_container
    command: [ "http", "--domain=delicate-elephant-close.ngrok-free.app", "backend:8080" ]
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_REGION=${NGROK_REGION}
    depends_on:
      - backend
    ports:
      - "4040:4040" # Expose ngrok web interface on port 4040 for monitoring
