version: '3'
services:
  backend:
    image: lightshark/kepler_galaxy_backend:1.3
    # for ali-cloud 
    # image: registry.cn-heyuan.aliyuncs.com/kepler_galaxy/kepler_galaxy:1.0
    container_name: backend_container
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
      - ./credentials.json:/app/credentials.json

  ngrok:
    image: ngrok/ngrok:latest
    # for ali-cloud
    #image: registry.cn-heyuan.aliyuncs.com/kepler_galaxy/ngrok:1.0
    container_name: ngrok_container
    command: [ "http", "--domain=equal-magnetic-pheasant.ngrok-free.app", "backend:8080" ]
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_REGION=${NGROK_REGION}
    depends_on:
      - backend
    ports:
      - "4040:4040" # Expose ngrok web interface on port 4040 for monitoring
