version: '3'
services:
  backend:
    image: krccr.ccs.tencentyun.com/kepler_galaxy/foxxy:1.0.2
    container_name: backend_container
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
      - ./credentials.json:/app/credentials.json
    environment:
      - ENV=prod

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_container
    command: [ "http", "--domain=equal-magnetic-pheasant.ngrok-free.app", "backend:8080" ]
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_REGION=${NGROK_REGION}
    depends_on:
      - backend
    ports:
      - "4040:4040"
